server:
  port: 4000

spring:
  data:
    mongodb:
      uri: mongodb+srv://chathruwanpahansith055:NdIbO840JXSZkqsw@paf.kelbuhn.mongodb.net/Pafproject?retryWrites=true&w=majority&appName=paf
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: gyu4w67nct4gr8o24crweprudg3raqw37grtewgm37g8rmyewuly8sw
  expiration: 86400000

file:
  upload-dir: ./uploads
