server:
  port: 4000

spring:
  data:
    mongodb:
      uri: mongodb+srv://aweeshainfo:rTS7SoEfhFhXtGkk@skill-share-paf.rdmrwm0.mongodb.net/pafProject?retryWrites=true&w=majority&appName=skill-share-paf
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: gyu4w67nct4gr8o24crweprudg3raqw37grtewgm37g8rmyewuly8sw
  expiration: 86400000

file:
  upload-dir: ./uploads
